const PartnerPrivacyPolicy = () => {
    return (
      <div className="flex flex-col w-full h-auto font-satoshi content-center items-start p-6 sm:p-8 md:p-12">
        <div className="flex flex-col w-full">
          <h1 className="text-black text-pretty text-3xl sm:text-4xl md:text-[35px] font-semibold ml-2 sm:ml-4 md:ml-6 mt-2 border-b border-gray-300 pb-4 sm:pb-5 md:pb-6 mb-6 sm:mb-7 md:mb-8 shadow-sm">
            Partner Application Privacy Policy
          </h1>
  
          <div className="text-base sm:text-lg md:text-[18px] justify-start items-start ml-2 sm:ml-4 md:ml-6 text-[#191020] font-satoshi">
            <p className="mb-4">
              Last updated: July 14, 2024
            </p>
            <p className="mb-4">
              This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You.
            </p>
            <p className="mb-4">
              We use Your Personal data to provide and improve the Service. By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy. This Privacy Policy has been created with the help of the Privacy Policy Generator.
            </p>
  
            <h2 className="text-black text-pretty text-xl sm:text-3xl md:text-[24px] font-bold mt-4">Interpretation and Definitions:</h2>
            <h2 className="text-black text-pretty text-lg sm:text-xl md:text-[22px] font-bold mt-6">Interpretation</h2>
            <p className="mb-4 mt-4">
              The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.
            </p>
  
            <h3 className="text-black text-pretty text-lg sm:text-xl md:text-[22px] font-bold mt-6">Definitions</h3>
            <p className="mb-4 mt-3">
              For the purposes of this Privacy Policy:
            </p>
            <ul className="list-disc ml-8 mb-4 mt-4">
              <li className="mb-1"><b>Partner Account</b> means a unique account created by the Canyfix team to access our Service.</li>
              <li className="mb-1"><b>Application</b> refers to Canyfix, the software program provided by the Company.</li>
              <li className="mb-1"><b>Company</b> (referred to as either "the Company", "We", "Us" or "Our" in this Agreement) refers to Canyfix, Shop 5, Sai Arcade, Chatrapati Shivaji Maharaj Chowk, next to Maharashtra bank, behind Kuba resturant, Bhanunagar Kalyan(West), Narayan Peth, Bhoiwada, Kalyan, Maharashtra 421306.</li>
              <li className="mb-1"><b>Country</b> refers to: Maharashtra, India</li>
              <li className="mb-1"><b>Device</b> means any device that can access the Service such as a computer, a cellphone or a digital tablet.</li>
              <li className="mb-1"><b>Personal Data</b> is any information that relates to an identified or identifiable individual store.</li>
              <li className="mb-1"><b>Service</b> refers to the Application.</li>
              <li className="mb-1"><b>Service Provider</b> means any natural or legal person who processes the data on behalf of the Company. It refers to third-party companies or individuals employed by the Company to facilitate the Service, to provide the Service on behalf of the Company, to perform services related to the Service or to assist the Company in analyzing how the Service is used.</li>
              <li className="mb-1"><b>Usage Data</b> refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).</li>
              <li className="mb-1"><b>You</b> means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.</li>
            </ul>
          </div>
        </div>
  
        <div className="flex flex-col w-full">
  
          <div className="flex flex-col mt-4">
            <h2 className="text-black text-pretty text-xl sm:text-3xl md:text-[24px] font-bold ml-2 sm:ml-4 md:ml-6 mt-4">
              Retention of Your Personal Data:
            </h2>
            <div className="flex flex-col text-base sm:text-lg md:text-[18px] ml-6 mt-4 space-y-4">
              <p className="mb-4">
                The Company will retain Your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. We will retain and use Your Personal Data to the extent necessary to comply with our legal obligations (for example, if we are required to retain your data to comply with applicable laws), resolve disputes, and enforce our legal agreements and policies.
              </p>
              <p className="mb-4">
                The Company will also retain Usage Data for internal analysis purposes. Usage Data is generally retained for a shorter period of time, except when this data is used to strengthen the security or to improve the functionality of Our Service, or We are legally obligated to retain this data for longer time periods.
              </p>
  
            </div>
          </div>
  
          <div className="flex flex-col mt-4">
            <h2 className="text-black text-pretty text-xl sm:text-3xl md:text-[24px] font-bold ml-2 sm:ml-4 md:ml-6 mt-4">
              Transfer of Your Personal Data:
            </h2>
            <div className="flex flex-col text-base sm:text-lg md:text-[18px] ml-6 mt-4 space-y-4">
              <p className="mb-4">
                Your information, including Personal Data, is processed at the Company's operating offices and in any other places where the parties involved in the processing are located. It means that this information may be transferred to — and maintained on — computers located outside of Your state, province, country or other governmental jurisdiction where the data protection laws may differ than those from Your jurisdiction.
              </p>
              <p className="mb-4">
                Your consent to this Privacy Policy followed by Your submission of such information represents Your agreement to that transfer.
              </p>
              <p className="mb-4">
                The Company will take all steps reasonably necessary to ensure that Your data is treated securely and in accordance with this Privacy Policy and no transfer of Your Personal Data will take place to an organization or a country unless there are adequate controls in place including the security of Your data and other personal information.
              </p>
            </div>
          </div>
  
          <div className="flex flex-col mt-4">
            <h2 className="text-black text-pretty text-xl sm:text-3xl md:text-[24px] font-bold ml-2 sm:ml-4 md:ml-6 mt-4">
              Delete Your Personal Data:
            </h2>
            <div className="flex flex-col text-base sm:text-lg md:text-[18px] ml-6 mt-4 space-y-4">
              <p className="mb-4">
                You have the right to delete or request that We assist in deleting the Personal Data that We have collected about You.
              </p>
              <p className="mb-4">
                Our Service may give You the ability to delete certain information about You from within the Service.
              </p>
              <p className="mb-4">
                You may update, amend, or delete Your information at any time by signing in to Your Account, if you have one, and visiting the account settings section that allows you to manage Your personal information. You may also contact Us to request access to, correct, or delete any personal information that You have provided to Us.
              </p>
              <p className="mb-4">
                Please note, however, that We may need to retain certain information when we have a legal obligation or lawful basis to do so.
              </p>
            </div>
          </div>
  
          <div className="flex flex-col mt-4">
            <h2 className="text-black text-pretty text-xl sm:text-3xl md:text-[24px] font-bold ml-2 sm:ml-4 md:ml-6 mt-4">
              Disclosure of Your Personal Data:
            </h2>
            <div className="flex flex-col text-base sm:text-lg md:text-[18px] ml-2 sm:ml-4 md:ml-6 mt-4">
              <h3 className="text-black text-pretty text-md sm:text-lg md:text-[20px] font-bold mt-3">Business Transactions</h3>
              <p className="mb-4 mt-2 ">
                If the Company is involved in a merger, acquisition or asset sale, Your Personal Data may be transferred. We will provide notice before Your Personal Data is transferred and becomes subject to a different Privacy Policy.
              </p>
  
              <h3 className="text-black text-pretty text-md sm:text-lg md:text-[20px] font-bold mt-3">Law enforcement</h3>
              <p className="mb-4 mt-2 ">
                Under certain circumstances, the Company may be required to disclose Your Personal Data if required to do so by law or in response to valid requests by public authorities (e.g. a court or a government agency).
              </p>
  
              <h3 className="text-black text-pretty text-md sm:text-lg md:text-[20px] font-bold mt-3">Other legal requirements</h3>
              <p className="mb-4 mt-2 ">
                The Company may disclose Your Personal Data in the good faith belief that such action is necessary to:
              </p>
              <ul className="list-disc ml-8 mb-4">
                <li className="mb-1">Comply with a legal obligation</li>
                <li className="mb-1">Protect and defend the rights or property of the Company</li>
                <li className="mb-1">Prevent or investigate possible wrongdoing in connection with the Service</li>
                <li className="mb-1">Protect the personal safety of Users of the Service or the public</li>
                <li className="mb-1">Protect against legal liability</li>
              </ul>
            </div>
          </div>
  
          <div className="flex flex-col mt-4">
            <h2 className="text-black text-pretty text-xl sm:text-3xl md:text-[24px] font-bold ml-2 sm:ml-4 md:ml-6 mt-4">
              Security of Your Personal Data:
            </h2>
            <div className="flex text-base sm:text-lg md:text-[18px] ml-2 sm:ml-4 md:ml-6 mt-4">
              <p>
                The security of Your Personal Data is important to Us, but remember that no method of transmission over the Internet, or method of electronic storage is 100% secure. While We strive to use commercially acceptable means to protect Your Personal Data, We cannot guarantee its absolute security.
              </p>
            </div>
          </div>
  
          <div className="flex flex-col mt-4">
            <h2 className="text-black text-pretty text-xl sm:text-3xl md:text-[24px] font-bold ml-2 sm:ml-4 md:ml-6 mt-4">
              Children's Privacy:
            </h2>
            <div className="flex flex-col text-base sm:text-lg md:text-[18px] ml-2 sm:ml-4 md:ml-6 mt-4 space-y-4">
              <p>
                Our Service does not address anyone under the age of 13. We do not knowingly collect personally identifiable information from anyone under the age of 13. If You are a parent or guardian and You are aware that Your child has provided Us with Personal Data, please contact Us. If We become aware that We have collected Personal Data from anyone under the age of 13 without verification of parental consent, We take steps to remove that information from Our servers.
              </p>
              <p>
                If We need to rely on consent as a legal basis for processing Your information and Your country requires consent from a parent, We may require Your parent's consent before We collect and use that information.
              </p>
            </div>
            <div className="flex flex-col text-base sm:text-lg md:text-[18px] ml-2 sm:ml-4 md:ml-6 mt-4 space-y-4">
              <h2 className="text-black text-pretty text-lg sm:text-xl md:text-[24px] font-bold mt-2">Links to Other Websites:</h2>
              <p className="mb-4">
                Our Service may contain links to other websites that are not operated by Us. If You click on a third party link, You will be directed to that third party's site. We strongly advise You to review the Privacy Policy of every site You visit.
              </p>
            </div>
  
          </div>
  
          <div className="flex flex-col mt-4">
            <h2 className="text-black text-pretty text-xl sm:text-3xl md:text-[24px] font-bold ml-2 sm:ml-4 md:ml-6 mt-4">
              Changes to This Privacy Policy:
            </h2>
            <div className="flex flex-col text-base sm:text-lg md:text-[18px] ml-2 sm:ml-4 md:ml-6 mt-4 space-y-2">
              <p>
                We may update Our Privacy Policy from time to time. We will notify You of any changes by posting the new Privacy Policy on this page.
              </p>
              <p>
                We will let You know via email and/or a prominent notice on Our Service, prior to the change becoming effective and update the "Last updated" date at the top of this Privacy Policy.
              </p>
              <p>You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy are effective when they are posted on this page.</p>
            </div>
          </div>
  
          <div className="flex flex-col mt-4">
            <h2 className="text-black text-pretty text-xl sm:text-3xl md:text-[24px] font-bold ml-2 sm:ml-4 md:ml-6 mt-4">
              Contact Us:
            </h2>
            <div className="flex flex-col text-base sm:text-lg md:text-[18px] ml-2 sm:ml-4 md:ml-6 mt-4 space-y-4">
              <p>
                If you have any questions about this Privacy Policy, You can contact us:
              </p>
              <ul className="list-disc ml-8 mb-4">
                <li className="mb-1">By email: support@canyfix.com</li>
                {/* <li className="mb-1">By visiting this page on our website: www.example.com/contact</li>
              <li className="mb-1">By phone number: +1234567890</li> */}
              </ul>
            </div>
          </div>
        </div>
      </div>
    );
  };
  
  export default PartnerPrivacyPolicy;
